language: go

go:
  - 1.6
  - 1.7
  - 1.8
  - tip

install:
    - go get -v github.com/Masterminds/glide
    - cd $GOPATH/src/github.com/Masterminds/glide && go install && cd -
    - glide install
    - go get golang.org/x/tools/cmd/cover
    - go get github.com/mattn/goveralls

script:
    - go test -v -covermode=count -coverprofile=coverage.out 
    - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN

notifications:
    email:
        - hapoon24@gmail.com